---
title: "Assignment7"
author: "Yi Wang"
format: html
editor: visual
---

```{R}

require(ISLR)

# Check dataset Smarket
?Smarket
names(Smarket)
summary(Smarket)

# Create a dataframe for data browsing
sm=Smarket

# Bivariate Plot of inter-lag correlations
pairs(Smarket,col=Smarket$Direction,cex=.5, pch=20)

# Logistic regression
glm.fit=glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume,
            data=Smarket,family=binomial)
summary(glm.fit)
glm.probs=predict(glm.fit,type="response") 
glm.probs[1:5]
glm.pred=ifelse(glm.probs>0.5,"Up","Down")
attach(Smarket)
table(glm.pred,Direction)
mean(glm.pred==Direction)

# Make training and test set for prediction
train = Year<2005
glm.fit=glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume,
            data=Smarket,family=binomial, subset=train)
glm.probs=predict(glm.fit,newdata=Smarket[!train,],type="response") 
glm.pred=ifelse(glm.probs >0.5,"Up","Down")
Direction.2005=Smarket$Direction[!train]
table(glm.pred,Direction.2005)
mean(glm.pred==Direction.2005)

#Fit smaller model
glm.fit=glm(Direction~Lag1+Lag2,
            data=Smarket,family=binomial, subset=train)
glm.probs=predict(glm.fit,newdata=Smarket[!train,],type="response") 
glm.pred=ifelse(glm.probs >0.5,"Up","Down")
table(glm.pred,Direction.2005)
mean(glm.pred==Direction.2005)

# Check accuracy rate
106/(76+106)

# Can you interpret the results?

```

# Answer: 

**Result Interpretation**

2a: In LDA, predictor variables are assumed to be normally distributed with equal variance, and the response variable must be categorical, as LDA is tailored for classification tasks.

2b: LDA is suitable for multiclass classification, while logistic regression is typically used for binary classification. Additionally, LDA imposes distributional assumptions on the data, unlike logistic regression.

2c: The Receiver Operating Characteristic (ROC) curve assesses the performance of a classifier model.

2d: Sensitivity measures the true positive rate, while specificity measures the true negative rate. Sensitivity is often prioritized due to the severe consequences of false positives, such as wrongful convictions. Both type I and II errors are undesirable, but high sensitivity is crucial.

2e: Based on the chart, sensitivity is deemed more critical for prediction.

3:

```{R}
prediction_error <- (252+23)/10000
cat("Prediction error:", formatC(prediction_error * 100, format = "f", digits = 2), "%\n")
```
