---
title: "Assignment 1 (& Prep for Class 2)"
author: "Wang"
---

**Team Project Brainstorm:**

-   Research Question

-   Hypothesis

-   Contribution & Impact

-   Data Source & Data Collection

-   Research Design

    -   Methods

**Prep for Class 2 – Comparing Breiman (2001) and Shmueli (2010):**

Breiman (2001) and Shmueli (2010) offer insightful discussions on different methodologies within statistical modeling, each addressing distinct but complementary aspects of the field.

Breiman's 2001 article, "Statistical Modeling: The Two Cultures," contrasts the data model and algorithmic model approaches. He criticizes the data model approach for its reliance on possibly unrealistic assumptions about how data is generated and advocates for the algorithmic model approach, which includes methods like decision trees and neural networks, for its flexibility and ability to manage complex data without predefined assumptions. Breiman calls for integrating both approaches to tackle real-world issues better, emphasizing the necessity of model validation through techniques like cross-validation.

Shmueli (2010), in "To Explain or to Predict? ", differentiates between explanatory and predictive modeling. She challenges the belief that explanatory power implies predictive accuracy, arguing that they fulfill different roles: explanatory modeling tests causal hypotheses, while predictive modeling forecasts future events.

Shmueli defends predictive modeling against academic biases, highlighting its potential to reveal new causal mechanisms and serve as a reality check for causal theories. She outlines four main differences between the two modeling types, including their approaches to causation, theory, focus (retrospective vs. prospective), and the bias-variance dilemma, advocating for a clear distinction and appreciation of both.

These two articles advocate for a broader, more inclusive approach to statistical modeling. Breiman (2001) focuses on the methodological divide and the potential of algorithmic models for real-world data, whereas Shmueli (2010) emphasizes the distinct but complementary roles of explanatory and predictive modeling. Both call for flexibility, rigorous validation, and a balanced use of modeling techniques to advance theoretical and practical applications in the field.
